"""sprint3_fir_schema

Revision ID: a0cd7d83a3b6
Revises: c8e30a9043dd
Create Date: 2026-07-23 01:08:54.235779

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a0cd7d83a3b6'
down_revision: Union[str, Sequence[str], None] = 'c8e30a9043dd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('act',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('case_category_master',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('case_status_master',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('caste_master',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('crime_head',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('designation_master',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('gravity_offence_master',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('occupation_master',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('rank_master',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('code', sa.String(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('religion_master',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('state_master',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('code', sa.String(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('unit_type_master',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('complainant_details',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('case_id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('age', sa.Integer(), nullable=True),
    sa.Column('gender', sa.String(), nullable=True),
    sa.Column('occupation_id', sa.String(), nullable=True),
    sa.Column('religion_id', sa.String(), nullable=True),
    sa.Column('caste_id', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['case_id'], ['cases.id'], ),
    sa.ForeignKeyConstraint(['caste_id'], ['caste_master.id'], ),
    sa.ForeignKeyConstraint(['occupation_id'], ['occupation_master.id'], ),
    sa.ForeignKeyConstraint(['religion_id'], ['religion_master.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('case_id')
    )
    op.create_table('crime_sub_head',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('crime_head_id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['crime_head_id'], ['crime_head.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('district_master',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('state_id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('code', sa.String(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['state_id'], ['state_master.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('section',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('act_id', sa.String(), nullable=False),
    sa.Column('section_number', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['act_id'], ['act.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('act_section_association',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('case_id', sa.String(), nullable=False),
    sa.Column('act_id', sa.String(), nullable=False),
    sa.Column('section_id', sa.String(), nullable=False),
    sa.Column('display_order', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['act_id'], ['act.id'], ),
    sa.ForeignKeyConstraint(['case_id'], ['cases.id'], ),
    sa.ForeignKeyConstraint(['section_id'], ['section.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('court_master',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('district_id', sa.String(), nullable=False),
    sa.Column('court_name', sa.String(), nullable=False),
    sa.Column('court_type', sa.String(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['district_id'], ['district_master.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('unit_master',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('district_id', sa.String(), nullable=False),
    sa.Column('unit_type_id', sa.String(), nullable=False),
    sa.Column('unit_name', sa.String(), nullable=False),
    sa.Column('code', sa.String(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['district_id'], ['district_master.id'], ),
    sa.ForeignKeyConstraint(['unit_type_id'], ['unit_type_master.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('employee_master',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('kgid', sa.String(), nullable=True),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('gender', sa.String(), nullable=True),
    sa.Column('dob', sa.DateTime(), nullable=True),
    sa.Column('appointment_date', sa.DateTime(), nullable=True),
    sa.Column('rank_id', sa.String(), nullable=True),
    sa.Column('designation_id', sa.String(), nullable=True),
    sa.Column('unit_id', sa.String(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['designation_id'], ['designation_master.id'], ),
    sa.ForeignKeyConstraint(['rank_id'], ['rank_master.id'], ),
    sa.ForeignKeyConstraint(['unit_id'], ['unit_master.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_employee_master_kgid'), 'employee_master', ['kgid'], unique=True)
    op.create_table('arrest_surrender',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('case_id', sa.String(), nullable=False),
    sa.Column('accused_person_id', sa.String(), nullable=False),
    sa.Column('event_type', sa.String(), nullable=False),
    sa.Column('event_date', sa.DateTime(), nullable=True),
    sa.Column('unit_id', sa.String(), nullable=True),
    sa.Column('investigating_officer_id', sa.String(), nullable=True),
    sa.Column('court_id', sa.String(), nullable=True),
    sa.Column('is_accused', sa.Boolean(), nullable=True),
    sa.Column('is_complainant_accused', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['accused_person_id'], ['persons.id'], ),
    sa.ForeignKeyConstraint(['case_id'], ['cases.id'], ),
    sa.ForeignKeyConstraint(['court_id'], ['court_master.id'], ),
    sa.ForeignKeyConstraint(['investigating_officer_id'], ['employee_master.id'], ),
    sa.ForeignKeyConstraint(['unit_id'], ['unit_master.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('case_fir_details',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('case_id', sa.String(), nullable=False),
    sa.Column('crime_no', sa.String(), nullable=False),
    sa.Column('case_no', sa.String(), nullable=True),
    sa.Column('crime_registered_date', sa.DateTime(), nullable=True),
    sa.Column('incident_from_date', sa.DateTime(), nullable=True),
    sa.Column('incident_to_date', sa.DateTime(), nullable=True),
    sa.Column('info_received_ps_date', sa.DateTime(), nullable=True),
    sa.Column('case_category_id', sa.String(), nullable=True),
    sa.Column('gravity_offence_id', sa.String(), nullable=True),
    sa.Column('crime_head_id', sa.String(), nullable=True),
    sa.Column('crime_sub_head_id', sa.String(), nullable=True),
    sa.Column('case_status_id', sa.String(), nullable=True),
    sa.Column('court_id', sa.String(), nullable=True),
    sa.Column('police_station_id', sa.String(), nullable=True),
    sa.Column('registering_officer_id', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['case_category_id'], ['case_category_master.id'], ),
    sa.ForeignKeyConstraint(['case_id'], ['cases.id'], ),
    sa.ForeignKeyConstraint(['case_status_id'], ['case_status_master.id'], ),
    sa.ForeignKeyConstraint(['court_id'], ['court_master.id'], ),
    sa.ForeignKeyConstraint(['crime_head_id'], ['crime_head.id'], ),
    sa.ForeignKeyConstraint(['crime_sub_head_id'], ['crime_sub_head.id'], ),
    sa.ForeignKeyConstraint(['gravity_offence_id'], ['gravity_offence_master.id'], ),
    sa.ForeignKeyConstraint(['police_station_id'], ['unit_master.id'], ),
    sa.ForeignKeyConstraint(['registering_officer_id'], ['employee_master.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('case_id')
    )
    op.create_index(op.f('ix_case_fir_details_crime_no'), 'case_fir_details', ['crime_no'], unique=True)
    op.create_table('chargesheet_details',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('case_id', sa.String(), nullable=False),
    sa.Column('chargesheet_date', sa.DateTime(), nullable=True),
    sa.Column('cs_type', sa.String(), nullable=True),
    sa.Column('filing_officer_id', sa.String(), nullable=True),
    sa.Column('remarks', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['case_id'], ['cases.id'], ),
    sa.ForeignKeyConstraint(['filing_officer_id'], ['employee_master.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('case_id')
    )
    op.add_column('persons', sa.Column('is_police', sa.Boolean(), nullable=True))
    op.add_column('persons', sa.Column('person_sort_id', sa.String(), nullable=True))
    op.add_column('users', sa.Column('employee_id', sa.String(), nullable=True))
    op.create_foreign_key(None, 'users', 'employee_master', ['employee_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.drop_column('users', 'employee_id')
    op.drop_column('persons', 'person_sort_id')
    op.drop_column('persons', 'is_police')
    op.drop_table('chargesheet_details')
    op.drop_index(op.f('ix_case_fir_details_crime_no'), table_name='case_fir_details')
    op.drop_table('case_fir_details')
    op.drop_table('arrest_surrender')
    op.drop_index(op.f('ix_employee_master_kgid'), table_name='employee_master')
    op.drop_table('employee_master')
    op.drop_table('unit_master')
    op.drop_table('court_master')
    op.drop_table('act_section_association')
    op.drop_table('section')
    op.drop_table('district_master')
    op.drop_table('crime_sub_head')
    op.drop_table('complainant_details')
    op.drop_table('unit_type_master')
    op.drop_table('state_master')
    op.drop_table('religion_master')
    op.drop_table('rank_master')
    op.drop_table('occupation_master')
    op.drop_table('gravity_offence_master')
    op.drop_table('designation_master')
    op.drop_table('crime_head')
    op.drop_table('caste_master')
    op.drop_table('case_status_master')
    op.drop_table('case_category_master')
    op.drop_table('act')
    # ### end Alembic commands ###
