"""Sprint 2 schema

Revision ID: c8e30a9043dd
Revises: 4059ce033d05
Create Date: 2026-07-23 01:03:27.409495

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c8e30a9043dd'
down_revision: Union[str, Sequence[str], None] = '4059ce033d05'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('persons', sa.Column('is_flagged_offender', sa.Boolean(), nullable=True))
    op.add_column('persons', sa.Column('mo_tags', sa.Text(), nullable=True))
    op.add_column('persons', sa.Column('first_recorded_date', sa.DateTime(), nullable=True))
    op.add_column('persons', sa.Column('last_recorded_date', sa.DateTime(), nullable=True))
    op.add_column('persons', sa.Column('age', sa.Integer(), nullable=True))
    op.add_column('persons', sa.Column('gender', sa.String(), nullable=True))
    op.add_column('persons', sa.Column('occupation', sa.String(), nullable=True))
    op.add_column('persons', sa.Column('education_level', sa.String(), nullable=True))
    op.add_column('persons', sa.Column('income_bracket', sa.String(), nullable=True))
    op.add_column('persons', sa.Column('area_type', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('persons', 'area_type')
    op.drop_column('persons', 'income_bracket')
    op.drop_column('persons', 'education_level')
    op.drop_column('persons', 'occupation')
    op.drop_column('persons', 'gender')
    op.drop_column('persons', 'age')
    op.drop_column('persons', 'last_recorded_date')
    op.drop_column('persons', 'first_recorded_date')
    op.drop_column('persons', 'mo_tags')
    op.drop_column('persons', 'is_flagged_offender')
    # ### end Alembic commands ###
